set_property PACKAGE_PIN {E19} [get_ports {sys_clk_p}]
set_property IOSTANDARD {LVDS} [get_ports {sys_clk_p}]

set_property PACKAGE_PIN {E18} [get_ports {sys_clk_n}]
set_property IOSTANDARD {LVDS} [get_ports {sys_clk_n}]

set_property PACKAGE_PIN {AV40} [get_ports {reset}]
set_property IOSTANDARD {LVCMOS18} [get_ports {reset}]

set_property PACKAGE_PIN {AM39} [get_ports {init_calib_complete}]
set_property IOSTANDARD {LVCMOS18} [get_ports {init_calib_complete}]

set_property PACKAGE_PIN {AV30} [get_ports {key}]
set_property IOSTANDARD {LVCMOS18} [get_ports {key}]
#set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
#set_property PACKAGE_PIN {R32} [get_ports {jtag_jtag_TCK}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TCK}]
#set_property PULLUP {TRUE} [get_ports {jtag_jtag_TCK}]
#set_property PACKAGE_PIN {W36} [get_ports {jtag_jtag_TMS}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TMS}]
#set_property PULLUP {TRUE} [get_ports {jtag_jtag_TMS}]
#set_property PACKAGE_PIN {W37} [get_ports {jtag_jtag_TDI}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDI}]
#set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDI}]
#set_property PACKAGE_PIN {V40} [get_ports {jtag_jtag_TDO}]
#set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDO}]
#set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDO}]
create_clock -name jtag_clk_pin -period 300 [get_ports {jtag_jtag_TCK}];
set_property CLOCK_DEDICATED_ROUTE {FALSE} [get_nets [get_ports {jtag_jtag_TCK}]]
set_property PACKAGE_PIN {BA21} [get_ports {jtag_jtag_TCK}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TCK}]
# set_property PULLUP {TRUE} [get_ports {jtag_jtag_TCK}]
set_property PACKAGE_PIN {BB21} [get_ports {jtag_jtag_TMS}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TMS}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TMS}]
set_property PACKAGE_PIN {BB24} [get_ports {jtag_jtag_TDI}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDI}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDI}]
set_property PACKAGE_PIN {BB23} [get_ports {jtag_jtag_TDO}]
set_property IOSTANDARD {LVCMOS18} [get_ports {jtag_jtag_TDO}]
set_property PULLUP {TRUE} [get_ports {jtag_jtag_TDO}]


set_property PACKAGE_PIN {AT32} [get_ports {uart_ctsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_ctsn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {uart_ctsn}]]]
set_property PACKAGE_PIN {AR34} [get_ports {uart_rtsn}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rtsn}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rtsn}]]]
set_property PACKAGE_PIN {AU33} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {AU36} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]

set_property PACKAGE_PIN {AN30} [get_ports {sdio_sdio_clk}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_clk}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_clk}]]]
set_property PACKAGE_PIN {AP30} [get_ports {sdio_sdio_cmd}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_cmd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_cmd}]]]
set_property PACKAGE_PIN {AR30} [get_ports {sdio_sdio_dat_0}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_0}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanout -flat -endpoints_only [get_ports {sdio_sdio_dat_0}]]]
set_property PACKAGE_PIN {AU31} [get_ports {sdio_sdio_dat_1}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_1}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_1}]]]
set_property PACKAGE_PIN {AV31} [get_ports {sdio_sdio_dat_2}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_2}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_2}]]]
set_property PACKAGE_PIN {AT30} [get_ports {sdio_sdio_dat_3}]
set_property IOSTANDARD {LVCMOS18} [get_ports {sdio_sdio_dat_3}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {sdio_sdio_dat_3}]]]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_cmd}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_0}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_1}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_2}]
set_property PULLUP {TRUE} [get_ports {sdio_sdio_dat_3}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets meisha_i/util_ds_buf_0/U0/IBUF_OUT[0]]
create_clock -name clk_in1 -period 5.000 -waveform {0 2.5} [get_pins meisha_i/clk_wiz_0/clk_in1]
create_clock -name clk_out2 -period 20.000 -waveform {0 2.5} [get_pins meisha_i/clk_wiz_0/clk_out2]
create_clock -name clk_out1 -period 20.000-waveform {0 10} [get_pins meisha_i/clk_wiz_0/clk_out1]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets meisha_i/clk_wiz_0/reset]