//`define VENDOR_RAM_EN
//`define TRC_CHECK
`define CHIPLINK_CONNECT_DIRECT_TL
//`define MSTD_CELL_EN
//`define RANDOM 1'b0
//`define TRACK_12T

//`ifdef VENDOR_RAM_EN
//    `define ROM_DUT_MEM_HIER tb.u_MEISHAV100_TOP.topDesign.topMod.maskROM.rom.U_ROM.u_SPLB40_2048X32BM1A.Memory
//`else
    `define ROM_DUT_MEM_HIER tb.u_MEISHAV100_TOP.topDesign.topMod.maskROM.rom.rom
//`endif

// std cell name define 

`ifdef TRACK_7T
    `define CK_BUF_STD_CELL_DONT_TOUCH BUFCKLEHMX2
    `define CK_AND2_STD_CELL_DONT_TOUCH AN2CKLEHMX8
    //`define CK_DELAY_STD_CELL_DONT_TOUCH DLYN1LEHMX1
    `define CK_GATE_STD_CELL_DONT_TOUCH GCKESLEHMX2
    `define CK_INV_STD_CELL_DONT_TOUCH INVCKLEHMX0P7
    `define CK_MUX2_STD_CELL_DONT_TOUCH MUX2CKLEHMX0P7
    `define CK_OR2_STD_CELL_DONT_TOUCH OR2CKLEHMX2
    `define CK_XOR2_STD_CELL_DONT_TOUCH XOR2CKLEHMX2
    `define REG_ASYNC_RESET_ENABLE_DONT_TOUCH QDFERBNLEHMX0P4
`elsif TRACK_9T
    `define CK_BUF_STD_CELL_DONT_TOUCH BUFCKLBHMX2
    `define CK_AND2_STD_CELL_DONT_TOUCH AN2CKLBHMX8
    `define CK_DELAY_STD_CELL_DONT_TOUCH DLYN1LBHMX3
    `define CK_GATE_STD_CELL_DONT_TOUCH GCKESLBHMX2
    `define CK_INV_STD_CELL_DONT_TOUCH INVCKLBHMX0P7
    `define CK_MUX2_STD_CELL_DONT_TOUCH MUX2CKLBHMX0P7
    `define CK_OR2_STD_CELL_DONT_TOUCH OR2CKLBHMX2
    `define CK_XOR2_STD_CELL_DONT_TOUCH XOR2CKLBHMX2
    `define REG_ASYNC_RESET_ENABLE_DONT_TOUCH QDFERBNLBHMX0P4
`elsif TRACK_12T
    `define CK_BUF_STD_CELL_DONT_TOUCH BUFCKLHHMX2
    `define CK_AND2_STD_CELL_DONT_TOUCH AN2CKLHHMX8
    `define CK_DELAY_STD_CELL_DONT_TOUCH DLYN1LHHMX3
    `define CK_GATE_STD_CELL_DONT_TOUCH GCKESLHHMX2
    `define CK_INV_STD_CELL_DONT_TOUCH INVCKLHHMX0P7
    `define CK_MUX2_STD_CELL_DONT_TOUCH MUX2CKLHHMX0P7
    `define CK_OR2_STD_CELL_DONT_TOUCH OR2CKLHHMX2
    `define CK_XOR2_STD_CELL_DONT_TOUCH XOR2CKLHHMX2
    `define REG_ASYNC_RESET_ENABLE_DONT_TOUCH QDFERBNLHHMX0P4
`else

`endif