module MemoryBus( 
  input         clock, 
  input         reset, 
  input         auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_ready, 
  output        auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_valid, 
  output [2:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_opcode, 
  output [2:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_param, 
  output [2:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_size, 
  output [6:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_source, 
  output [31:0] auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_address, 
  output [7:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_mask, 
  output [63:0] auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_data, 
  output        auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_corrupt, 
  output        auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_ready, 
  input         auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_valid, 
  input  [2:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_opcode, 
  input  [1:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_param, 
  input  [2:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_size, 
  input  [6:0]  auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_source, 
  input         auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_sink, 
  input         auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_denied, 
  input  [63:0] auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_data, 
  input         auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_corrupt, 
  output        auto_coupler_from_coherence_manager_binder_in_a_ready, 
  input         auto_coupler_from_coherence_manager_binder_in_a_valid, 
  input  [2:0]  auto_coupler_from_coherence_manager_binder_in_a_bits_opcode, 
  input  [2:0]  auto_coupler_from_coherence_manager_binder_in_a_bits_param, 
  input  [2:0]  auto_coupler_from_coherence_manager_binder_in_a_bits_size, 
  input  [6:0]  auto_coupler_from_coherence_manager_binder_in_a_bits_source, 
  input  [31:0] auto_coupler_from_coherence_manager_binder_in_a_bits_address, 
  input  [7:0]  auto_coupler_from_coherence_manager_binder_in_a_bits_mask, 
  input  [63:0] auto_coupler_from_coherence_manager_binder_in_a_bits_data, 
  input         auto_coupler_from_coherence_manager_binder_in_a_bits_corrupt, 
  input         auto_coupler_from_coherence_manager_binder_in_d_ready, 
  output        auto_coupler_from_coherence_manager_binder_in_d_valid, 
  output [2:0]  auto_coupler_from_coherence_manager_binder_in_d_bits_opcode, 
  output [1:0]  auto_coupler_from_coherence_manager_binder_in_d_bits_param, 
  output [2:0]  auto_coupler_from_coherence_manager_binder_in_d_bits_size, 
  output [6:0]  auto_coupler_from_coherence_manager_binder_in_d_bits_source, 
  output        auto_coupler_from_coherence_manager_binder_in_d_bits_sink, 
  output        auto_coupler_from_coherence_manager_binder_in_d_bits_denied, 
  output [63:0] auto_coupler_from_coherence_manager_binder_in_d_bits_data, 
  output        auto_coupler_from_coherence_manager_binder_in_d_bits_corrupt 
);
  wire  memory_bus_xbar_clock; 
  wire  memory_bus_xbar_reset; 
  wire  memory_bus_xbar_auto_in_a_ready; 
  wire  memory_bus_xbar_auto_in_a_valid; 
  wire [2:0] memory_bus_xbar_auto_in_a_bits_opcode; 
  wire [2:0] memory_bus_xbar_auto_in_a_bits_param; 
  wire [2:0] memory_bus_xbar_auto_in_a_bits_size; 
  wire [6:0] memory_bus_xbar_auto_in_a_bits_source; 
  wire [31:0] memory_bus_xbar_auto_in_a_bits_address; 
  wire [7:0] memory_bus_xbar_auto_in_a_bits_mask; 
  wire [63:0] memory_bus_xbar_auto_in_a_bits_data; 
  wire  memory_bus_xbar_auto_in_a_bits_corrupt; 
  wire  memory_bus_xbar_auto_in_d_ready; 
  wire  memory_bus_xbar_auto_in_d_valid; 
  wire [2:0] memory_bus_xbar_auto_in_d_bits_opcode; 
  wire [1:0] memory_bus_xbar_auto_in_d_bits_param; 
  wire [2:0] memory_bus_xbar_auto_in_d_bits_size; 
  wire [6:0] memory_bus_xbar_auto_in_d_bits_source; 
  wire  memory_bus_xbar_auto_in_d_bits_sink; 
  wire  memory_bus_xbar_auto_in_d_bits_denied; 
  wire [63:0] memory_bus_xbar_auto_in_d_bits_data; 
  wire  memory_bus_xbar_auto_in_d_bits_corrupt; 
  wire  memory_bus_xbar_auto_out_a_ready; 
  wire  memory_bus_xbar_auto_out_a_valid; 
  wire [2:0] memory_bus_xbar_auto_out_a_bits_opcode; 
  wire [2:0] memory_bus_xbar_auto_out_a_bits_param; 
  wire [2:0] memory_bus_xbar_auto_out_a_bits_size; 
  wire [6:0] memory_bus_xbar_auto_out_a_bits_source; 
  wire [31:0] memory_bus_xbar_auto_out_a_bits_address; 
  wire [7:0] memory_bus_xbar_auto_out_a_bits_mask; 
  wire [63:0] memory_bus_xbar_auto_out_a_bits_data; 
  wire  memory_bus_xbar_auto_out_a_bits_corrupt; 
  wire  memory_bus_xbar_auto_out_d_ready; 
  wire  memory_bus_xbar_auto_out_d_valid; 
  wire [2:0] memory_bus_xbar_auto_out_d_bits_opcode; 
  wire [1:0] memory_bus_xbar_auto_out_d_bits_param; 
  wire [2:0] memory_bus_xbar_auto_out_d_bits_size; 
  wire [6:0] memory_bus_xbar_auto_out_d_bits_source; 
  wire  memory_bus_xbar_auto_out_d_bits_sink; 
  wire  memory_bus_xbar_auto_out_d_bits_denied; 
  wire [63:0] memory_bus_xbar_auto_out_d_bits_data; 
  wire  memory_bus_xbar_auto_out_d_bits_corrupt; 
  wire  coupler_from_coherence_manager_clock; 
  wire  coupler_from_coherence_manager_reset; 
  wire  coupler_from_coherence_manager_auto_binder_in_a_ready; 
  wire  coupler_from_coherence_manager_auto_binder_in_a_valid; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_in_a_bits_opcode; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_in_a_bits_param; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_in_a_bits_size; 
  wire [6:0] coupler_from_coherence_manager_auto_binder_in_a_bits_source; 
  wire [31:0] coupler_from_coherence_manager_auto_binder_in_a_bits_address; 
  wire [7:0] coupler_from_coherence_manager_auto_binder_in_a_bits_mask; 
  wire [63:0] coupler_from_coherence_manager_auto_binder_in_a_bits_data; 
  wire  coupler_from_coherence_manager_auto_binder_in_a_bits_corrupt; 
  wire  coupler_from_coherence_manager_auto_binder_in_d_ready; 
  wire  coupler_from_coherence_manager_auto_binder_in_d_valid; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_in_d_bits_opcode; 
  wire [1:0] coupler_from_coherence_manager_auto_binder_in_d_bits_param; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_in_d_bits_size; 
  wire [6:0] coupler_from_coherence_manager_auto_binder_in_d_bits_source; 
  wire  coupler_from_coherence_manager_auto_binder_in_d_bits_sink; 
  wire  coupler_from_coherence_manager_auto_binder_in_d_bits_denied; 
  wire [63:0] coupler_from_coherence_manager_auto_binder_in_d_bits_data; 
  wire  coupler_from_coherence_manager_auto_binder_in_d_bits_corrupt; 
  wire  coupler_from_coherence_manager_auto_binder_out_a_ready; 
  wire  coupler_from_coherence_manager_auto_binder_out_a_valid; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_out_a_bits_opcode; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_out_a_bits_param; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_out_a_bits_size; 
  wire [6:0] coupler_from_coherence_manager_auto_binder_out_a_bits_source; 
  wire [31:0] coupler_from_coherence_manager_auto_binder_out_a_bits_address; 
  wire [7:0] coupler_from_coherence_manager_auto_binder_out_a_bits_mask; 
  wire [63:0] coupler_from_coherence_manager_auto_binder_out_a_bits_data; 
  wire  coupler_from_coherence_manager_auto_binder_out_a_bits_corrupt; 
  wire  coupler_from_coherence_manager_auto_binder_out_d_ready; 
  wire  coupler_from_coherence_manager_auto_binder_out_d_valid; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_out_d_bits_opcode; 
  wire [1:0] coupler_from_coherence_manager_auto_binder_out_d_bits_param; 
  wire [2:0] coupler_from_coherence_manager_auto_binder_out_d_bits_size; 
  wire [6:0] coupler_from_coherence_manager_auto_binder_out_d_bits_source; 
  wire  coupler_from_coherence_manager_auto_binder_out_d_bits_sink; 
  wire  coupler_from_coherence_manager_auto_binder_out_d_bits_denied; 
  wire [63:0] coupler_from_coherence_manager_auto_binder_out_d_bits_data; 
  wire  coupler_from_coherence_manager_auto_binder_out_d_bits_corrupt; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_clock; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_reset; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_ready; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_valid; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_opcode; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_param; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_size; 
  wire [6:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_source; 
  wire [31:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_address; 
  wire [7:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_mask; 
  wire [63:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_data; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_corrupt; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_ready; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_valid; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_opcode; 
  wire [1:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_param; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_size; 
  wire [6:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_source; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_sink; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_denied; 
  wire [63:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_data; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_corrupt; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_ready; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_valid; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_opcode; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_param; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_size; 
  wire [6:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_source; 
  wire [31:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_address; 
  wire [7:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_mask; 
  wire [63:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_data; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_corrupt; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_ready; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_valid; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_opcode; 
  wire [1:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_param; 
  wire [2:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_size; 
  wire [6:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_source; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_sink; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_denied; 
  wire [63:0] coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_data; 
  wire  coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_corrupt; 
  TLXbar_6 memory_bus_xbar ( 
    .clock(memory_bus_xbar_clock),
    .reset(memory_bus_xbar_reset),
    .auto_in_a_ready(memory_bus_xbar_auto_in_a_ready),
    .auto_in_a_valid(memory_bus_xbar_auto_in_a_valid),
    .auto_in_a_bits_opcode(memory_bus_xbar_auto_in_a_bits_opcode),
    .auto_in_a_bits_param(memory_bus_xbar_auto_in_a_bits_param),
    .auto_in_a_bits_size(memory_bus_xbar_auto_in_a_bits_size),
    .auto_in_a_bits_source(memory_bus_xbar_auto_in_a_bits_source),
    .auto_in_a_bits_address(memory_bus_xbar_auto_in_a_bits_address),
    .auto_in_a_bits_mask(memory_bus_xbar_auto_in_a_bits_mask),
    .auto_in_a_bits_data(memory_bus_xbar_auto_in_a_bits_data),
    .auto_in_a_bits_corrupt(memory_bus_xbar_auto_in_a_bits_corrupt),
    .auto_in_d_ready(memory_bus_xbar_auto_in_d_ready),
    .auto_in_d_valid(memory_bus_xbar_auto_in_d_valid),
    .auto_in_d_bits_opcode(memory_bus_xbar_auto_in_d_bits_opcode),
    .auto_in_d_bits_param(memory_bus_xbar_auto_in_d_bits_param),
    .auto_in_d_bits_size(memory_bus_xbar_auto_in_d_bits_size),
    .auto_in_d_bits_source(memory_bus_xbar_auto_in_d_bits_source),
    .auto_in_d_bits_sink(memory_bus_xbar_auto_in_d_bits_sink),
    .auto_in_d_bits_denied(memory_bus_xbar_auto_in_d_bits_denied),
    .auto_in_d_bits_data(memory_bus_xbar_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt(memory_bus_xbar_auto_in_d_bits_corrupt),
    .auto_out_a_ready(memory_bus_xbar_auto_out_a_ready),
    .auto_out_a_valid(memory_bus_xbar_auto_out_a_valid),
    .auto_out_a_bits_opcode(memory_bus_xbar_auto_out_a_bits_opcode),
    .auto_out_a_bits_param(memory_bus_xbar_auto_out_a_bits_param),
    .auto_out_a_bits_size(memory_bus_xbar_auto_out_a_bits_size),
    .auto_out_a_bits_source(memory_bus_xbar_auto_out_a_bits_source),
    .auto_out_a_bits_address(memory_bus_xbar_auto_out_a_bits_address),
    .auto_out_a_bits_mask(memory_bus_xbar_auto_out_a_bits_mask),
    .auto_out_a_bits_data(memory_bus_xbar_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt(memory_bus_xbar_auto_out_a_bits_corrupt),
    .auto_out_d_ready(memory_bus_xbar_auto_out_d_ready),
    .auto_out_d_valid(memory_bus_xbar_auto_out_d_valid),
    .auto_out_d_bits_opcode(memory_bus_xbar_auto_out_d_bits_opcode),
    .auto_out_d_bits_param(memory_bus_xbar_auto_out_d_bits_param),
    .auto_out_d_bits_size(memory_bus_xbar_auto_out_d_bits_size),
    .auto_out_d_bits_source(memory_bus_xbar_auto_out_d_bits_source),
    .auto_out_d_bits_sink(memory_bus_xbar_auto_out_d_bits_sink),
    .auto_out_d_bits_denied(memory_bus_xbar_auto_out_d_bits_denied),
    .auto_out_d_bits_data(memory_bus_xbar_auto_out_d_bits_data),
    .auto_out_d_bits_corrupt(memory_bus_xbar_auto_out_d_bits_corrupt)
  );
  SimpleLazyModule_25 coupler_from_coherence_manager ( 
    .clock(coupler_from_coherence_manager_clock),
    .reset(coupler_from_coherence_manager_reset),
    .auto_binder_in_a_ready(coupler_from_coherence_manager_auto_binder_in_a_ready),
    .auto_binder_in_a_valid(coupler_from_coherence_manager_auto_binder_in_a_valid),
    .auto_binder_in_a_bits_opcode(coupler_from_coherence_manager_auto_binder_in_a_bits_opcode),
    .auto_binder_in_a_bits_param(coupler_from_coherence_manager_auto_binder_in_a_bits_param),
    .auto_binder_in_a_bits_size(coupler_from_coherence_manager_auto_binder_in_a_bits_size),
    .auto_binder_in_a_bits_source(coupler_from_coherence_manager_auto_binder_in_a_bits_source),
    .auto_binder_in_a_bits_address(coupler_from_coherence_manager_auto_binder_in_a_bits_address),
    .auto_binder_in_a_bits_mask(coupler_from_coherence_manager_auto_binder_in_a_bits_mask),
    .auto_binder_in_a_bits_data(coupler_from_coherence_manager_auto_binder_in_a_bits_data),
    .auto_binder_in_a_bits_corrupt(coupler_from_coherence_manager_auto_binder_in_a_bits_corrupt),
    .auto_binder_in_d_ready(coupler_from_coherence_manager_auto_binder_in_d_ready),
    .auto_binder_in_d_valid(coupler_from_coherence_manager_auto_binder_in_d_valid),
    .auto_binder_in_d_bits_opcode(coupler_from_coherence_manager_auto_binder_in_d_bits_opcode),
    .auto_binder_in_d_bits_param(coupler_from_coherence_manager_auto_binder_in_d_bits_param),
    .auto_binder_in_d_bits_size(coupler_from_coherence_manager_auto_binder_in_d_bits_size),
    .auto_binder_in_d_bits_source(coupler_from_coherence_manager_auto_binder_in_d_bits_source),
    .auto_binder_in_d_bits_sink(coupler_from_coherence_manager_auto_binder_in_d_bits_sink),
    .auto_binder_in_d_bits_denied(coupler_from_coherence_manager_auto_binder_in_d_bits_denied),
    .auto_binder_in_d_bits_data(coupler_from_coherence_manager_auto_binder_in_d_bits_data),
    .auto_binder_in_d_bits_corrupt(coupler_from_coherence_manager_auto_binder_in_d_bits_corrupt),
    .auto_binder_out_a_ready(coupler_from_coherence_manager_auto_binder_out_a_ready),
    .auto_binder_out_a_valid(coupler_from_coherence_manager_auto_binder_out_a_valid),
    .auto_binder_out_a_bits_opcode(coupler_from_coherence_manager_auto_binder_out_a_bits_opcode),
    .auto_binder_out_a_bits_param(coupler_from_coherence_manager_auto_binder_out_a_bits_param),
    .auto_binder_out_a_bits_size(coupler_from_coherence_manager_auto_binder_out_a_bits_size),
    .auto_binder_out_a_bits_source(coupler_from_coherence_manager_auto_binder_out_a_bits_source),
    .auto_binder_out_a_bits_address(coupler_from_coherence_manager_auto_binder_out_a_bits_address),
    .auto_binder_out_a_bits_mask(coupler_from_coherence_manager_auto_binder_out_a_bits_mask),
    .auto_binder_out_a_bits_data(coupler_from_coherence_manager_auto_binder_out_a_bits_data),
    .auto_binder_out_a_bits_corrupt(coupler_from_coherence_manager_auto_binder_out_a_bits_corrupt),
    .auto_binder_out_d_ready(coupler_from_coherence_manager_auto_binder_out_d_ready),
    .auto_binder_out_d_valid(coupler_from_coherence_manager_auto_binder_out_d_valid),
    .auto_binder_out_d_bits_opcode(coupler_from_coherence_manager_auto_binder_out_d_bits_opcode),
    .auto_binder_out_d_bits_param(coupler_from_coherence_manager_auto_binder_out_d_bits_param),
    .auto_binder_out_d_bits_size(coupler_from_coherence_manager_auto_binder_out_d_bits_size),
    .auto_binder_out_d_bits_source(coupler_from_coherence_manager_auto_binder_out_d_bits_source),
    .auto_binder_out_d_bits_sink(coupler_from_coherence_manager_auto_binder_out_d_bits_sink),
    .auto_binder_out_d_bits_denied(coupler_from_coherence_manager_auto_binder_out_d_bits_denied),
    .auto_binder_out_d_bits_data(coupler_from_coherence_manager_auto_binder_out_d_bits_data),
    .auto_binder_out_d_bits_corrupt(coupler_from_coherence_manager_auto_binder_out_d_bits_corrupt)
  );
  SimpleLazyModule_26 coupler_to_memory_controller_named_xilinxvc707mig ( 
    .clock(coupler_to_memory_controller_named_xilinxvc707mig_clock),
    .reset(coupler_to_memory_controller_named_xilinxvc707mig_reset),
    .auto_picker_in_a_ready(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_ready),
    .auto_picker_in_a_valid(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_valid),
    .auto_picker_in_a_bits_opcode(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_opcode),
    .auto_picker_in_a_bits_param(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_param),
    .auto_picker_in_a_bits_size(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_size),
    .auto_picker_in_a_bits_source(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_source),
    .auto_picker_in_a_bits_address(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_address),
    .auto_picker_in_a_bits_mask(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_mask),
    .auto_picker_in_a_bits_data(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_data),
    .auto_picker_in_a_bits_corrupt(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_corrupt),
    .auto_picker_in_d_ready(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_ready),
    .auto_picker_in_d_valid(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_valid),
    .auto_picker_in_d_bits_opcode(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_opcode),
    .auto_picker_in_d_bits_param(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_param),
    .auto_picker_in_d_bits_size(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_size),
    .auto_picker_in_d_bits_source(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_source),
    .auto_picker_in_d_bits_sink(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_sink),
    .auto_picker_in_d_bits_denied(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_denied),
    .auto_picker_in_d_bits_data(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_data),
    .auto_picker_in_d_bits_corrupt(coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_corrupt),
    .auto_xilinxvc707mig_out_a_ready(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_ready),
    .auto_xilinxvc707mig_out_a_valid(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_valid),
    .auto_xilinxvc707mig_out_a_bits_opcode(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_opcode),
    .auto_xilinxvc707mig_out_a_bits_param(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_param),
    .auto_xilinxvc707mig_out_a_bits_size(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_size),
    .auto_xilinxvc707mig_out_a_bits_source(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_source),
    .auto_xilinxvc707mig_out_a_bits_address(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_address),
    .auto_xilinxvc707mig_out_a_bits_mask(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_mask),
    .auto_xilinxvc707mig_out_a_bits_data(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_data),
    .auto_xilinxvc707mig_out_a_bits_corrupt(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_corrupt),
    .auto_xilinxvc707mig_out_d_ready(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_ready),
    .auto_xilinxvc707mig_out_d_valid(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_valid),
    .auto_xilinxvc707mig_out_d_bits_opcode(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_opcode),
    .auto_xilinxvc707mig_out_d_bits_param(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_param),
    .auto_xilinxvc707mig_out_d_bits_size(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_size),
    .auto_xilinxvc707mig_out_d_bits_source(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_source),
    .auto_xilinxvc707mig_out_d_bits_sink(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_sink),
    .auto_xilinxvc707mig_out_d_bits_denied(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_denied),
    .auto_xilinxvc707mig_out_d_bits_data(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_data),
    .auto_xilinxvc707mig_out_d_bits_corrupt(coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_corrupt)
  );
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_valid = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_valid; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_opcode = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_opcode; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_param = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_param; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_size = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_size; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_source = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_source; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_address = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_address; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_mask = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_mask; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_data = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_data; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_bits_corrupt = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_bits_corrupt; 
  assign auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_ready = coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_ready; 
  assign auto_coupler_from_coherence_manager_binder_in_a_ready = coupler_from_coherence_manager_auto_binder_in_a_ready; 
  assign auto_coupler_from_coherence_manager_binder_in_d_valid = coupler_from_coherence_manager_auto_binder_in_d_valid; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_opcode = coupler_from_coherence_manager_auto_binder_in_d_bits_opcode; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_param = coupler_from_coherence_manager_auto_binder_in_d_bits_param; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_size = coupler_from_coherence_manager_auto_binder_in_d_bits_size; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_source = coupler_from_coherence_manager_auto_binder_in_d_bits_source; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_sink = coupler_from_coherence_manager_auto_binder_in_d_bits_sink; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_denied = coupler_from_coherence_manager_auto_binder_in_d_bits_denied; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_data = coupler_from_coherence_manager_auto_binder_in_d_bits_data; 
  assign auto_coupler_from_coherence_manager_binder_in_d_bits_corrupt = coupler_from_coherence_manager_auto_binder_in_d_bits_corrupt; 
  assign memory_bus_xbar_clock = clock; 
  assign memory_bus_xbar_reset = reset; 
  assign memory_bus_xbar_auto_in_a_valid = coupler_from_coherence_manager_auto_binder_out_a_valid; 
  assign memory_bus_xbar_auto_in_a_bits_opcode = coupler_from_coherence_manager_auto_binder_out_a_bits_opcode; 
  assign memory_bus_xbar_auto_in_a_bits_param = coupler_from_coherence_manager_auto_binder_out_a_bits_param; 
  assign memory_bus_xbar_auto_in_a_bits_size = coupler_from_coherence_manager_auto_binder_out_a_bits_size; 
  assign memory_bus_xbar_auto_in_a_bits_source = coupler_from_coherence_manager_auto_binder_out_a_bits_source; 
  assign memory_bus_xbar_auto_in_a_bits_address = coupler_from_coherence_manager_auto_binder_out_a_bits_address; 
  assign memory_bus_xbar_auto_in_a_bits_mask = coupler_from_coherence_manager_auto_binder_out_a_bits_mask; 
  assign memory_bus_xbar_auto_in_a_bits_data = coupler_from_coherence_manager_auto_binder_out_a_bits_data; 
  assign memory_bus_xbar_auto_in_a_bits_corrupt = coupler_from_coherence_manager_auto_binder_out_a_bits_corrupt; 
  assign memory_bus_xbar_auto_in_d_ready = coupler_from_coherence_manager_auto_binder_out_d_ready; 
  assign memory_bus_xbar_auto_out_a_ready = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_ready; 
  assign memory_bus_xbar_auto_out_d_valid = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_valid; 
  assign memory_bus_xbar_auto_out_d_bits_opcode = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_opcode; 
  assign memory_bus_xbar_auto_out_d_bits_param = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_param; 
  assign memory_bus_xbar_auto_out_d_bits_size = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_size; 
  assign memory_bus_xbar_auto_out_d_bits_source = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_source; 
  assign memory_bus_xbar_auto_out_d_bits_sink = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_sink; 
  assign memory_bus_xbar_auto_out_d_bits_denied = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_denied; 
  assign memory_bus_xbar_auto_out_d_bits_data = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_data; 
  assign memory_bus_xbar_auto_out_d_bits_corrupt = coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_bits_corrupt; 
  assign coupler_from_coherence_manager_clock = clock; 
  assign coupler_from_coherence_manager_reset = reset; 
  assign coupler_from_coherence_manager_auto_binder_in_a_valid = auto_coupler_from_coherence_manager_binder_in_a_valid; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_opcode = auto_coupler_from_coherence_manager_binder_in_a_bits_opcode; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_param = auto_coupler_from_coherence_manager_binder_in_a_bits_param; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_size = auto_coupler_from_coherence_manager_binder_in_a_bits_size; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_source = auto_coupler_from_coherence_manager_binder_in_a_bits_source; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_address = auto_coupler_from_coherence_manager_binder_in_a_bits_address; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_mask = auto_coupler_from_coherence_manager_binder_in_a_bits_mask; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_data = auto_coupler_from_coherence_manager_binder_in_a_bits_data; 
  assign coupler_from_coherence_manager_auto_binder_in_a_bits_corrupt = auto_coupler_from_coherence_manager_binder_in_a_bits_corrupt; 
  assign coupler_from_coherence_manager_auto_binder_in_d_ready = auto_coupler_from_coherence_manager_binder_in_d_ready; 
  assign coupler_from_coherence_manager_auto_binder_out_a_ready = memory_bus_xbar_auto_in_a_ready; 
  assign coupler_from_coherence_manager_auto_binder_out_d_valid = memory_bus_xbar_auto_in_d_valid; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_opcode = memory_bus_xbar_auto_in_d_bits_opcode; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_param = memory_bus_xbar_auto_in_d_bits_param; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_size = memory_bus_xbar_auto_in_d_bits_size; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_source = memory_bus_xbar_auto_in_d_bits_source; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_sink = memory_bus_xbar_auto_in_d_bits_sink; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_denied = memory_bus_xbar_auto_in_d_bits_denied; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_data = memory_bus_xbar_auto_in_d_bits_data; 
  assign coupler_from_coherence_manager_auto_binder_out_d_bits_corrupt = memory_bus_xbar_auto_in_d_bits_corrupt; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_clock = clock; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_reset = reset; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_valid = memory_bus_xbar_auto_out_a_valid; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_opcode = memory_bus_xbar_auto_out_a_bits_opcode; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_param = memory_bus_xbar_auto_out_a_bits_param; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_size = memory_bus_xbar_auto_out_a_bits_size; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_source = memory_bus_xbar_auto_out_a_bits_source; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_address = memory_bus_xbar_auto_out_a_bits_address; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_mask = memory_bus_xbar_auto_out_a_bits_mask; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_data = memory_bus_xbar_auto_out_a_bits_data; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_a_bits_corrupt = memory_bus_xbar_auto_out_a_bits_corrupt; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_picker_in_d_ready = memory_bus_xbar_auto_out_d_ready; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_a_ready = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_a_ready; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_valid = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_valid; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_opcode = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_opcode; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_param = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_param; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_size = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_size; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_source = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_source; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_sink = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_sink; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_denied = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_denied; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_data = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_data; 
  assign coupler_to_memory_controller_named_xilinxvc707mig_auto_xilinxvc707mig_out_d_bits_corrupt = auto_coupler_to_memory_controller_named_xilinxvc707mig_xilinxvc707mig_out_d_bits_corrupt; 
endmodule
