# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/meisha_ok/meisha.xdc

# Block Designs: bd/meisha/meisha.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha || ORIG_REF_NAME==meisha}]

# IP: bd/meisha/ip/meisha_clk_wiz_0_0/meisha_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_clk_wiz_0_0 || ORIG_REF_NAME==meisha_clk_wiz_0_0}]

# IP: bd/meisha/ip/meisha_util_ds_buf_0_0/meisha_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_ds_buf_0_0 || ORIG_REF_NAME==meisha_util_ds_buf_0_0}]

# IP: bd/meisha/ip/meisha_mig_7series_0_0/meisha_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_mig_7series_0_0 || ORIG_REF_NAME==meisha_mig_7series_0_0}]

# IP: bd/meisha/ip/meisha_axi_interconnect_0_0/meisha_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_axi_interconnect_0_0 || ORIG_REF_NAME==meisha_axi_interconnect_0_0}]

# IP: bd/meisha/ip/meisha_proc_sys_reset_0_0/meisha_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_proc_sys_reset_0_0 || ORIG_REF_NAME==meisha_proc_sys_reset_0_0}]

# IP: bd/meisha/ip/meisha_util_vector_logic_0_1/meisha_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_vector_logic_0_1 || ORIG_REF_NAME==meisha_util_vector_logic_0_1}]

# IP: bd/meisha/ip/meisha_proc_sys_reset_0_1/meisha_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_proc_sys_reset_0_1 || ORIG_REF_NAME==meisha_proc_sys_reset_0_1}]

# IP: bd/meisha/ip/meisha_util_vector_logic_1_0/meisha_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_vector_logic_1_0 || ORIG_REF_NAME==meisha_util_vector_logic_1_0}]

# IP: bd/meisha/ip/meisha_clk_wiz_1_0/meisha_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_clk_wiz_1_0 || ORIG_REF_NAME==meisha_clk_wiz_1_0}]

# IP: bd/meisha/ip/meisha_util_vector_logic_0_0/meisha_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_vector_logic_0_0 || ORIG_REF_NAME==meisha_util_vector_logic_0_0}]

# IP: bd/meisha/ip/meisha_DevKitWrapper_0_0/meisha_DevKitWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_DevKitWrapper_0_0 || ORIG_REF_NAME==meisha_DevKitWrapper_0_0}]

# IP: bd/meisha/ip/meisha_xlconstant_0_0/meisha_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_xlconstant_0_0 || ORIG_REF_NAME==meisha_xlconstant_0_0}]

# IP: bd/meisha/ip/meisha_util_vector_logic_3_0/meisha_util_vector_logic_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_vector_logic_3_0 || ORIG_REF_NAME==meisha_util_vector_logic_3_0}]

# IP: bd/meisha/ip/meisha_util_vector_logic_4_0/meisha_util_vector_logic_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_util_vector_logic_4_0 || ORIG_REF_NAME==meisha_util_vector_logic_4_0}]

# IP: bd/meisha/ip/meisha_chiplink_master_0_1/meisha_chiplink_master_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_chiplink_master_0_1 || ORIG_REF_NAME==meisha_chiplink_master_0_1}]

# IP: bd/meisha/ip/meisha_auto_cc_0/meisha_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==meisha_auto_cc_0 || ORIG_REF_NAME==meisha_auto_cc_0}]

# XDC: bd/meisha/meisha_ooc.xdc
